services:
  prod:
    image: higgsfield_api_prod
    build:
      context: higgsfield-api
      dockerfile: Dockerfile
    container_name: higgsfield_api_prod
    volumes:
      - ./higgsfield-api:/usr/src/higgsfield-api
    env_file:
      - .env
    ports:
      - "8018:8000"
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped
    labels:
      - "autoheal=true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/$UUID_TEST_CHECK"]
      interval: 60s
      timeout: 10s
      retries: 1
  test:
    image: higgsfield_api_test
    build:
      context: higgsfield-api
      dockerfile: Dockerfile
    volumes:
      - ./higgsfield-api:/usr/src/higgsfield-api
    container_name: higgsfield_api_test
    command: >
      sh -c "pytest -v -s ./tests"
    restart: no

  autoheal:
    image: willfarrell/autoheal:1.2.0
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

